export enum ActionTypes {
  // authentication
  REGISTER_START = 'REGISTER_START',
  REGISTER_END = 'REGISTER_END',
  REGISTER_FAIL = 'REGISTER_FAIL',
  AUTHENTICATION_START = 'AUTHENTICATION_START',
  AUTHENTICATION_END = 'AUTHENTICATION_END',
  AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL',
  SING_OUT = 'SING_OUT',
  UNSET_ERROR = 'UNSET_ERROR',
  // diary
  ADD_PRODUCT = 'ADD_PRODUCT',
  REMOVE_PRODUCT = 'REMOVE_PRODUCT',
  SET_SKIN = 'SET_SKIN',
  SAVE_DIARY = 'SAVE_DIARY',
  CLEAR_DIARY = 'CLEAR_DIARY',
  SET_SINGLE_DIARY_DAY = 'SET_SINGLE_DIARY_DAY',
  CHANGE_DATE = 'CHANGE_DATE',
  ANALYZE_FULL_DIARY = 'ANALYZE_FULL_DIARY',
  SET_ANALYSIS_LOADING = 'SET_ANALYSIS_LOADING',
  SET_ADDED_PRODUCTS_LIST = 'SET_ADDED_PRODUCTS_LIST',
  // modals
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
}
